apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:  ## MatchLabels not used like in Deployment because Service can only match on labels so implied
    app: second-app
    tier: backend
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer
